
CREATE INDEX idx_person_name ON person (UPPER(name));

SET ENABLE_SEQSCAN TO ON;
EXPLAIN ANALYZE 
SELECT name
FROM person
WHERE UPPER(name) IN (
SELECT UPPER(name) FROM person
)

SET ENABLE_SEQSCAN TO OFF;
EXPLAIN ANALYZE 
SELECT name
FROM person
WHERE UPPER(name) IN (
SELECT UPPER(name) FROM person
)